version: '3.7'

services:

  # APACHE WITH PHP
  app.catroweb.dev:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: app.catroweb.dev
    image: app.catroweb.dev
    depends_on:
      - db.catroweb.dev
      - ldap.catroweb.dev
    ports:
      - 80:80
    volumes:
      - ./../tests:/var/www/catroweb/tests:cached
      - ./../templates:/var/www/catroweb/templates:cached
      - ./../translations:/var/www/catroweb/translations:cached
      - ./../src:/var/www/catroweb/src:cached
      - /vendor
      - /node_modules

  # DATABASE
  db.catroweb.dev:
    image: mariadb:10.3
    container_name: db.catroweb.dev
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=symfony
    ports:
      - 3306:3306

  # LDAP
  ldap.catroweb.dev:
    image: osixia/openldap:1.2.5
    container_name: ldap.catroweb.dev
    environment:
      - LDAP_ADMIN_PASSWORD=secret
      - LDAP_BASE_DN='ou=users, dc=example, dc=org'
    ports:
      - 8001:636

  # PHPMYADMIN
  phpmyadmin.catroweb.dev:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin.catroweb.dev
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8002:80
    volumes:
      - /sessions
    external_links:
      - db.catroweb.dev:db
    depends_on:
      - db.catroweb.dev